# Generated by Django 5.2.4 on 2025-08-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinbuilt',
            old_name='username',
            new_name='user',
        ),
    ]
