# Generated by Django 5.2.4 on 2025-08-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_username_customerinbuilt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinbuilt',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
