# Generated by Django 5.2.4 on 2025-08-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_shippingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingpayment',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
